language: node_js
node_js:
- 14.16.0
install: yarn
script: gatsby build
deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: "first-gatsby-use"
  skip_cleanup: true
  acl: public_read
  local_dir: public